# Generated by Django 4.2.9 on 2024-01-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_manager", "0002_remove_subscription_app_plan_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="app",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_app",
                to="app_manager.app",
            ),
        ),
    ]
